CSHARP/OENIK_PROG3_2019_2_O0U6EC/CraftCamp.Web/Models/Places.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace CraftCamp.Web.Models
{
    public class Places
    {
        [Display(Name="Place ID")]
        [Required]
        public int ID { get; set; }

        [Display(Name = "Place Name")]
        [Required]
        public string Name { get; set; }

        [Display(Name = "Place Phone number")]
        [Required]
        public string Phone { get; set; }

        [Display(Name = "Place Capacity")]
        [Required]
        public int Capacity { get; set; }

        [Display(Name = "City of the Place")]
        [Required]
        public string City { get; set; }

        [Display(Name = "Street of the Place")]
        [Required]
        public string Street { get; set; }
    }
}

CSHARP/OENIK_PROG3_2019_2_O0U6EC/CraftCamp.Web/Models/PlacesViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CraftCamp.Web.Models
{
    public class PlacesViewModel
    {
        public Places newPlace { get; set; }
        public Places editedPlace { get; set; }
        public List<Places> ListOfPlaces { get; set; }
    }
}

CSHARP/OENIK_PROG3_2019_2_O0U6EC/CraftCamp.Web/Controllers/PlacesController.cs
using AutoMapper;
using CraftCamp.Data;
using CraftCamp.Logic;
using CraftCamp.Repository;
using CraftCamp.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CraftCamp.Web.Controllers
{
    public class PlacesController : Controller
    {
        IHelyszinLogic hLogic;
        PlacesViewModel model;
        IMapper mapper;
        IMapper mapperReverse;
        public PlacesController()
        {
            CraftCampDBEntities ctx = new CraftCampDBEntities();
            HelyszinRepository repo = new HelyszinRepository(ctx);
            hLogic = new HelyszinLogic(repo);
            mapper = MapperFactory.CreateMapper();
            mapperReverse = MapperFactory.CreateMapperReverse();
            model = new PlacesViewModel();
            model.editedPlace = new Places();
            model.newPlace = new Places();
            var places = hLogic.Listazas().ToList();
            model.ListOfPlaces = mapper.Map<List<CraftCamp.Data.Helyszinek>, List<CraftCamp.Web.Models.Places>>(places);
        }

        private Places GetPlaceModel(int id)
        {
            Helyszinek onePlace = hLogic.GetOne(id);
            return mapper.Map<Helyszinek, Places>(onePlace);
        }

        // GET: Places
        public ActionResult Index()
        {
            model.newPlace = new Places();
            return View("PlacesIndex",model);
        }

        // GET: Places/Details/5
        public ActionResult Details(int id)
        {
            return View("PlacesDetails",GetPlaceModel(id));
        }

        [HttpPost]
        public ActionResult Add(Places place)
        {
            Helyszinek ujHelyszin = mapperReverse.Map<Places, Helyszinek>(place);
            int count = hLogic.Listazas().Count();
            
            hLogic.Hozzaadas(ujHelyszin);
            model.newPlace = new Places();

            if (count < hLogic.Listazas().Count())
                TempData["editResult"] = "Insert OK!";
            else
                TempData["editResult"] = "Insert FAILED!";
            return RedirectToAction("Index", model);
        }

        // GET: Places/Edit/5
        public ActionResult Edit(int id)
        {
            model.editedPlace = GetPlaceModel(id);
            return View("PlacesIndex", model);
        }

        [HttpPost]
        public ActionResult Edit(Places place)
        {
            Helyszinek originalHelyszin = hLogic.GetOne(place.ID);
            Helyszinek modHelyszin = mapperReverse.Map<Places, Helyszinek>(place);

            if (originalHelyszin.Nev != modHelyszin.Nev)
                hLogic.Nev_Modositas(place.ID, place.Name);
            if (originalHelyszin.Maxhely != modHelyszin.Maxhely)
                hLogic.Maxhely_Modositas(place.ID, place.Capacity);
            if (originalHelyszin.Telefonszam != modHelyszin.Telefonszam)
                hLogic.Telefonszam_Modositas(place.ID, place.Phone);
            if (originalHelyszin.Telepules != modHelyszin.Telepules)
                hLogic.Telepules_Modositas(place.ID, modHelyszin.Telepules);
            if (originalHelyszin.Utca != modHelyszin.Utca)
                hLogic.Utca_Modositas(place.ID, modHelyszin.Utca);

            model.editedPlace = new Places();
            TempData["editResult"] = "Edit OK!";
            return RedirectToAction("Index", model);
        }

        // GET: Places/Delete/5
        public ActionResult Delete(int id)
        {
            if(hLogic.Torles(id))
                TempData["editResult"] = "Delete OK!";
            else
                TempData["editResult"] = "Delete FAIL!";
            return RedirectToAction("Index");
        }
    }
}

CSHARP/OENIK_PROG3_2019_2_O0U6EC/CraftCamp.Web/Views/Places/PlacesAdd.cshtml
@model CraftCamp.Web.Models.Places

@{
    ViewBag.Title = "PlacesAdd";
}

<h2>Add new Place!</h2>

@using (Html.BeginForm("Add", "Places", FormMethod.Post))
{
    @Html.ValidationSummary()

    @Html.AntiForgeryToken()

    <div class="editor-label">@Html.LabelFor(m => m.Name)</div>
    <div class="editor-field">@Html.EditorFor(m => m.Name)</div>

    <div class="editor-label">@Html.LabelFor(m => m.Phone)</div>
    <div class="editor-field">@Html.EditorFor(m => m.Phone)</div>

    <div class="editor-label">@Html.LabelFor(m => m.Capacity)</div>
    <div class="editor-field">@Html.EditorFor(m => m.Capacity)</div>

    <div class="editor-label">@Html.LabelFor(m => m.City)</div>
    <div class="editor-field">@Html.EditorFor(m => m.City)</div>

    <div class="editor-label">@Html.LabelFor(m => m.Street)</div>
    <div class="editor-field">@Html.EditorFor(m => m.Street)</div>

    <input type="submit" value="CREATE" />
}

CSHARP/OENIK_PROG3_2019_2_O0U6EC/CraftCamp.Web/Views/Places/PlacesDetails.cshtml
@model CraftCamp.Web.Models.Places
@{
    ViewBag.Title = "PlacesDetails";
}

<h2>Details of the Place!</h2>

@Html.ActionLink("Back to the list", "Index")

<table border="1">
    <tr>
        <td>@Html.DisplayNameFor(m => m.ID)</td>
        <td>@Html.DisplayFor(m => m.ID)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.Name)</td>
        <td>@Html.DisplayFor(m => m.Name)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.Phone)</td>
        <td>@Html.DisplayFor(m => m.Phone)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.Capacity)</td>
        <td>@Html.DisplayFor(m => m.Capacity)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.City)</td>
        <td>@Html.DisplayFor(m => m.City)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.Street)</td>
        <td>@Html.DisplayFor(m => m.Street)</td>
    </tr>
</table>

CSHARP/OENIK_PROG3_2019_2_O0U6EC/CraftCamp.Web/Views/Places/PlacesEdit.cshtml
@model CraftCamp.Web.Models.Places

@{
    ViewBag.Title = "PlacesEdit";
}

<h2>Edit the selected Place!</h2>

@using (Html.BeginForm("Edit", "Places", FormMethod.Post))
{
    @Html.ValidationSummary()

    @Html.AntiForgeryToken()

    @Html.HiddenFor(m => m.ID)

    <div class="editor-label">@Html.LabelFor(m => m.Name)</div>
    <div class="editor-field">@Html.EditorFor(m => m.Name)</div>

    <div class="editor-label">@Html.LabelFor(m => m.Phone)</div>
    <div class="editor-field">@Html.EditorFor(m => m.Phone)</div>

    <div class="editor-label">@Html.LabelFor(m => m.Capacity)</div>
    <div class="editor-field">@Html.EditorFor(m => m.Capacity)</div>

    <div class="editor-label">@Html.LabelFor(m => m.City)</div>
    <div class="editor-field">@Html.EditorFor(m => m.City)</div>

    <div class="editor-label">@Html.LabelFor(m => m.Street)</div>
    <div class="editor-field">@Html.EditorFor(m => m.Street)</div>

    <input type="submit" value="MODIFY" />
}

CSHARP/OENIK_PROG3_2019_2_O0U6EC/CraftCamp.Web/Views/Places/PlacesIndex.cshtml
@model CraftCamp.Web.Models.PlacesViewModel
@{
    ViewBag.Title = "PlacesIndex";
}

<h2>Places - CRUD</h2>

<p style="color:red">
    @TempData["editResult"]
</p>
<hr style="border:10px solid green; border-radius:5px;" />
@Html.Partial("PlacesAdd", Model.newPlace)
<hr style="border:10px solid green; border-radius:5px;" />
@Html.Partial("PlacesList", Model.ListOfPlaces)
<hr style="border:10px solid green; border-radius:5px;" />
@if (Model.editedPlace.ID != 0)
{
    @Html.Partial("PlacesEdit", Model.editedPlace)
    <hr style="border:10px solid green; border-radius:5px;" />
}

CSHARP/OENIK_PROG3_2019_2_O0U6EC/CraftCamp.Web/Views/Places/PlacesList.cshtml
@model IEnumerable<CraftCamp.Web.Models.Places>

@{
    ViewBag.Title = "PlacesList";
}
<h2>List of the Places!</h2>

@if (Model.Count() == 0)
{
    <p>No data in the database!!!</p>
}
else
{
    <table border="1">
        <tr>
            <th>@Html.DisplayNameFor(m => m.First().ID)</th>
            <th>@Html.DisplayNameFor(m => m.First().Name)</th>
            <th>@Html.DisplayNameFor(m => m.First().Phone)</th>
            <th>@Html.DisplayNameFor(m => m.First().Capacity)</th>
            <th>@Html.DisplayNameFor(m => m.First().City)</th>
            <th>@Html.DisplayNameFor(m => m.First().Street)</th>
            <th>Datasheet</th>
            <th>Edit</th>
            <th>Delete</th>
        </tr>
        @foreach (var item in Model)
        {
        <tr>
            <td>@Html.DisplayFor(m => item.ID)</td>
            <td>@Html.DisplayFor(m => item.Name)</td>
            <td>@Html.DisplayFor(m => item.Phone)</td>
            <td>@Html.DisplayFor(m => item.Capacity)</td>
            <td>@Html.DisplayFor(m => item.City)</td>
            <td>@Html.DisplayFor(m => item.Street)</td>
            <td>@Html.ActionLink("[SHOW]", "Details", new { id = item.ID })</td>
            <td>@Html.ActionLink("[EDIT]", "Edit", new { id = item.ID })</td>
            <td>@Html.ActionLink("[DEL]", "Delete", new { id = item.ID })</td>
        </tr>
        }
    </table>
}